version: '3.8'

services:
  accounts:
    restart: unless-stopped
    build:
      context: ./accounts
      dockerfile: ../Dockerfile.rust
    container_name: accounts
    network_mode: "host"
    environment:
      PORT: 4001
      SUBGRAPH_DELAY_MS: ${ACCOUNTS_SUBGRAPH_DELAY_MS}
    healthcheck:
        test: ["CMD", "/usr/lib/apt/apt-helper", "download-file", "http://0.0.0.0:4001/graphql", "temp"]
        interval: 3s
        timeout: 5s
        retries: 10
  inventory:
    restart: unless-stopped
    build:
      context: ./inventory
      dockerfile: ../Dockerfile.rust
    container_name: inventory 
    network_mode: "host"
    environment:
      PORT: 4002
      SUBGRAPH_DELAY_MS: ${ACCOUNTS_SUBGRAPH_DELAY_MS}
    healthcheck:
        test: ["CMD", "/usr/lib/apt/apt-helper", "download-file", "http://0.0.0.0:4002/graphql", "temp"]
        interval: 3s
        timeout: 5s
        retries: 10
  products:
    restart: unless-stopped
    build:
      context: ./products
      dockerfile: ../Dockerfile.rust
    container_name: products 
    network_mode: "host"
    environment:
      PORT: 4003
      SUBGRAPH_DELAY_MS: ${ACCOUNTS_SUBGRAPH_DELAY_MS}
    healthcheck:
        test: ["CMD", "/usr/lib/apt/apt-helper", "download-file", "http://0.0.0.0:4003/graphql", "temp"]
        interval: 3s
        timeout: 5s
        retries: 10
  reviews:
    restart: unless-stopped
    build:
      context: ./reviews
      dockerfile: ../Dockerfile.rust
    container_name: reviews
    network_mode: "host"
    environment:
      PORT: 4004
      SUBGRAPH_DELAY_MS: ${ACCOUNTS_SUBGRAPH_DELAY_MS}
    healthcheck:
        test: ["CMD", "/usr/lib/apt/apt-helper", "download-file", "http://0.0.0.0:4004/graphql", "temp"]
        interval: 3s
        timeout: 5s
        retries: 10

