[package]
name = "accounts"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-graphql = { version = "6.0.11", features = ["apollo_tracing"] }
async-graphql-axum = "6.0.11"
axum = "0.6.20"
lazy_static = "1.4.0"
rand = "0.8.5"
tokio = { version = "1.34.0", features = ["rt-multi-thread", "full"] }
async-trait = "0.1"
chrono = "0.4"

[[bin]]
name = "subgraph"
path = "subgraph.rs"
